<?php
	require_once('dto/DbObject.php');
	require_once('dto/Task.php');
	require_once('dto/Event.php');
	require_once('dto/ProcessDefinition.php');
	require_once('dto/Process.php');
	require_once('dto/VariableMap.php');
	require_once('persistence/ProcessStore.php');
	require_once('persistence/FileStore.php');
	require_once('persistence/CouchDbStore.php');
	require_once('persistence/InMemoryStore.php');
	require_once('XmlAdapter.php');
	require_once('ProcessInstance.php');
	require_once('BpmnEngine.php');
	require_once('elements/BpmnElementHandler.php');
	require_once('elements/DefaultBpmnElementHandler.php');
	require_once('elements/GatewayHandler.php');
	require_once('elements/EventHandler.php');
	require_once('elements/TaskHandler.php');
	require_once('elements/AbstractEventImpl.php');
	require_once('elements/AbstractMessageEventImpl.php');
	require_once('elements/TimerEventImpl.php');
	require_once('elements/AbstractTaskImpl.php');
	require_once('elements/AbstractServiceTaskImpl.php');
	require_once('elements/AbstractUserTaskImpl.php');
	require_once('configuration.php');

