<?php
	require_once('dto/DbObject.php');
	require_once('dto/Task.php');
	require_once('dto/Event.php');
	require_once('dto/ProcessDefinition.php');
	require_once('dto/Process.php');
	require_once('dto/VariableMap.php');
	require_once('persistence/ProcessStore.php');
	require_once('persistence/FileStore.php');
	require_once('persistence/CouchDbStore.php');
	require_once('persistence/InMemoryStore.php');
	require_once('XmlAdapter.php');
	require_once('ProcessInstance.php');
	require_once('BpmnEngine.php');
	require_once('AbstractMessageEventImpl.php');
	require_once('AbstractTaskImpl.php');
	require_once('AbstractServiceTaskImpl.php');
	require_once('AbstractUserTaskImpl.php');
?>