<?php
	require_once('DbObject.php');
	require_once('Task.php');
	require_once('Event.php');
	require_once('ProcessDefinition.php');
	require_once('ProcessStore.php');
	require_once('FileStore.php');
	require_once('XmlAdapter.php');
	require_once('VariableMap.php');
	require_once('Process.php');
	require_once('ProcessInstance.php');
	require_once('BpmnEngine.php');
	require_once('AbstractMessageEventImpl.php');
	require_once('AbstractTaskImpl.php');
	require_once('AbstractServiceTaskImpl.php');
	require_once('AbstractUserTaskImpl.php');
?>